language: ruby
before_install:
  - gem install bundler

script: 
  - rake build
  - rake spec
  
#notifications:
#  email:
#  - niklaus.giger@member.fsf.org

rvm:
  - ruby-head
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-19mode
  - rbx-18mode
  - jruby-head
  - jruby-19mode
  - jruby-18mode
  - ree
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 1.8.7
    - rvm: ruby-head
    - rvm: rbx-19mode
    - rvm: rbx-18mode
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: jruby-18mode
    - rvm: ree